### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [sutambe/LEESA#1]
I would like to point out that identifiers like “[`__LEESA_H`](https://github.com/sutambe/LEESA/blob/0be452fbafd32454a8a05e67ce28f59083bb3c60/include/LEESA/LEESA.h#L1 "Update candidate")” and “[`__SEQUENCE_HPP`](https://github.com/sutambe/LEESA/blob/d08ac7a3d8c9acf46fa98487236f93889d029796/include/LEESA/Sequence.hpp#L1 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by sutambe** [comment]
@elfring I agree. It's a dead project. Don't worry about it. I'm curious though what brought you here?

**Comment by elfring** [comment]
>It's a dead project.

This is a pity.

Would you like to help to improve the situation in the presented software area further anyhow?


>I'm curious though what brought you here?

I am looking again for better ways to [perform safe and efficient data processing with information from XML files](https://stackoverflow.com/questions/9387610/what-xml-parser-should-i-use-in-c "What XML parser should I use in C++?").

**Comment by sutambe** [comment]
> XML files.

Is XML still a thing? ;)

I would be happy if someone finds a use for this library. Fixing the library code is the easy part. Updating XML data binding compiler (CodeSynthesis XSD or any other) is perhaps harder. However, if the XML schema for your project is not changing frequently, XSD-generated code can be adapted in place.

**Comment by elfring** [comment]
>Fixing the library code is the easy part.

This sound promising.

* Many software components were improved in the meantime.
* How are the chances for corresponding updates in this C++ class library?
* Would you like to support further software evolution here?

**Comment by sutambe** [comment]
> Many software components were improved in the meantime.

Which components are you talking about?

> How are the chances for corresponding updates in this C++ class library?

What "corresponding" updates are you talking about?

> Would you like to support further software evolution here?

Can you give me some context of what you are trying to achieve.

I pushed a change that fixes reserved identifier violation.

**Comment by elfring** [comment]
>Which components are you talking about?

Examples:
* [C++ standard versions](https://en.wikipedia.org/wiki/C%2B%2B#Standardization "Software evolution for C++") (and compilers)
* [Boost class libraries](https://www.boost.org/users/news/ "C++ libraries")


>What "corresponding" updates are you talking about?

I guess that [your development experiences increased also during the years](https://cpptruths.blogspot.com/ "Blog by Sumant Tambe") so that more changes could eventually be considered.


>Can you give me some context of what you are trying to achieve.

I would find it nice if this software library will become better reusable so that XML data processing can be performed by C++ class and function templates (together with XPath support).


>I pushed a change that fixes reserved identifier violation.

Thanks for [your improvement of affected include guards](https://github.com/sutambe/LEESA/commit/509eec6854560dda8fca3010a28deb7c12978513 "Fixed include guards and a basic tuneup").

**Comment by sutambe** [comment]
@elfring From your activity in github, it seems you have posted the "reserved identifier violation" issue for dozens if not hundreds of projects. Some other common errors as well. It's all welcome, IMO. Makes me wonder, if you are developing a new static analyzer and testing it across public repos in github?

**Comment by sutambe** [comment]
> I would find it nice if this software library will become better reusable so that XML data processing can be performed by C++ class and function templates (together with XPath support).

Interesting. That's a very broad scope. Not conducive for productivity without a series of focussed low-hanging improvements to bootstrap a cold project. An actual use-case is certainly more motivating to me. I'll see what I can do.

**Comment by elfring** [comment]
>From your activity in github, …

I reported various issues in different issue trackers through the years.


>Makes me wonder, if you are developing a new static analyzer …

Not really. - But I am trained to notice improvement possibilities while I am trying to contribute also to a few software analysis tools.


>… bootstrap a cold project.

I am generally interested in another software refresh.


>An actual use-case is certainly more motivating to me.

Do you need concrete XML files as examples for further incentives (or can the motivation increase based on other ingredients which I would usually also appreciate)?

**Comment by sutambe** [comment]
> Do you need concrete XML files as examples

No. A real person trying to get some real work done but running into issues is what's needed.

@elfring Any thoughts on [user who persistently trolls open source codebases opening pedantic and vague issues](https://twitter.com/wesmckinn/status/715690973171306496)?

Closing this issue on that note. LOL!

**Comment by elfring** [comment]
>A real person trying to get some real work done but running into issues is what's needed.

I stumble on development challenges at various places. Would you still like to contribute to any remaining issues?


>LOL!

I hope that you can build a better impression from my published activities.
