### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [sutambe/LEESA#2]
I suggest to reuse a higher level build system than [your current make scripts](https://github.com/sutambe/LEESA/blob/509eec6854560dda8fca3010a28deb7c12978513/tests/library-xsd/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by sutambe** [comment]
Good suggestion. Irrespective of whether you are a bot or not. Closing as it's not a priority.

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.10/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?
